### ISSUE TITLE
Upgrade .NET Core 3.1 ?

### ISSUE THREAD

**Issue by doggy8088** [GregTrevellick/CleanArchitecture#16]
Does this [Clean Architecture](https://marketplace.visualstudio.com/items?itemName=GregTrevellick.CleanArchitecture) extension will upgrade to .NET Core 3.x?

**Comment by GregTrevellick** [comment]
Hi I am upgrading in in the next few days, will close this issue once upgraded. Thanks

**Comment by GregTrevellick** [comment]
Hi this is now updated to net core 3 now
