### ISSUE TITLE
Handlers Name Space?

### ISSUE THREAD

**Issue by jakeuj** [GregTrevellick/CleanArchitecture#17]
Which handler's namesapce is better, CleanArchitecture.Core.Services or CleanArchitecture.Core.Handlers?
BTW, example handler ItemCompletedEmailNotificationHandler's namesapce is CleanArchitecture.Core.Services.

**Comment by GregTrevellick** [comment]
Hi, thanks for your interest, but questions like this should be sent to Steve Smith at https://github.com/ardalis/CleanArchitecture
