### ISSUE TITLE
Create New Solution from Template

### ISSUE THREAD

**Issue by davekauffman** [GregTrevellick/CleanArchitecture#18]
The project names and base namespace all remain CleanArchitecture when creating a new project.

I would expect the namespace and project base names to take on the name entered in the create new project dialog.

**Comment by GregTrevellick** [comment]
Thanks Dave for this - I've re-opened the issue as it is a valid one. Surprised no one has raised it before. No idea when I can address though, but will keep it open.

**Comment by ardalis** [comment]
Hey @GregTrevellick do you want me to reach out to the community to see if someone can help with this? Also, should we do an update some time in the next month or so since a lot of changes have been made in the last 6 months?

**Comment by GregTrevellick** [comment]
Hi Steve, thanks for reminding me about this. I'll pull in the last 6 months changes very soon (hopefully this week some time).  I think I know how to address the namespace issue, so will try to address ASAP but reaching out would certainly be useful in case my free time evaporates. Thanks.

**Comment by ardalis** [comment]
Ok, I'll try to follow up in a week and see if you need help or have it all in hand. Thanks!

**Comment by GregTrevellick** [comment]
@ardalis see #19

**Comment by Amitpnk** [comment]
hi @ardalis @GregTrevellick ,

Is issue still open? shall I work on it?

**Comment by GregTrevellick** [comment]
Hi @Amitpnk yes issue is still open, would be great if you can work on it. Thanks.

**Comment by Amitpnk** [comment]
Thanks @GregTrevellick for your comment. Will fix this in few days.

**Comment by GregTrevellick** [comment]
Yep, master is the latest. 🙂

**Comment by Amitpnk** [comment]
Hi @GregTrevellick ,

Issue has been fixed and raised [PR-20]( https://github.com/GregTrevellick/CleanArchitecture/pull/20) 

Not able to see detail of it, as I don't have permission to see on snyk app. 
Please have look at it :)

Regards,
Amit Naik

**Comment by GregTrevellick** [comment]
Fixed - thank you Amit

**Comment by GregTrevellick** [comment]
@ardalis @Amitpnk v1.0.20 now published to marketplace :-)

**Comment by davekauffman** [comment]
Thanks Greg

**Comment by ardalis** [comment]
Awesome, thanks all!
